export const ladies = [
  {
    key: "Offers",
    key_data: ["Jeans starting 1299", "Tops under 999", "Sports Bra from ₹999"],
  },
  {
    key: "New In",
    key_data: ["View All"],
  },
  {
    key: "Clothing",
    key_data: [
      "View All",
      "Tops",
      "Dresses",
      "Shirts & Blouses",
      "Linen clothing",
      "Jeans",
      "Trousers",
      "Skirts",
      "Shorts",
      "Nightwear",
      "Basics",
      "Sweatshirts & Hoodies",
      "Knitwear",
      "Sweaters & Cardigans",
      "Jackets & Coats",
      "Blazers & Waistcoats",
      "Lingerie",
      "Swimwear & Beachwear",
    ],
  },
  {
    key: "Sport",
    key_data: [
      "View all",
      "New In",
      "Leggings & Tights",
      "Sport Bras",
      "Tops",
      "Hoodies & Sweatshirts",
      "Trousers & Joggers",
      "Shorts",
      "Dresses",
      "Outerwear",
      "Accessories & Equipment",
      "Socks",
      "Active Swimwear",
      "Maternity",
    ],
  },
  {
    key: "Accessories",
    key_data: [
      "View all",
      "Bags",
      "Jewellery",
      "Sunglasses",
      "Hair Accessories",
      "Belts",
      "Gloves",
      "Hats",
      "Scarves",
    ],
  },
  {
    key: "Shoes",
    key_data: [
      "View all",
      "Boots",
      "Flats",
      "Heels",
      "Loafers",
      "Sandals",
      "Slippers",
      "Slingback",
    ],
  },
  {
    key: "Sale",
    key_data: [
      "View all",
      "Dresses",
      "Skirts",
      "Tops",
      "Shirts & Blouses",
      "Sweatshirts & Hoodies",
      "Cardigans & Jumpers",
      "Blazers & Waistcoats",
      "Jackets & Coats",
      "Trousers",
      "Jeans",
      "Shorts",
      "Jumpsuits",
      "Nightwear & Loungewear",
      "Lingerie",
      "Socks & Tights",
      "Swimwear",
      "Maternity Wear",
      "Basics",
      "Premium Selection",
      "Accessories",
      "Shoes",
      "Sport",
      "Beauty",
    ],
  },
  {
    key: "Additional",
    key_data: ["Premium Selection", "Care products", "All Brands"],
  },
];
export const men = [
  {
    key: "Offers",
    key_data: [
      "T-shirt: From ₹399",
      "Shirts: From ₹1299",
      "Jeans: From ₹1799",
      "Sale: Up to 70%",
    ],
  },
  {
    key: "New In",
    key_data: ["View All", "Accessories", "Clothes"],
  },
  {
    key: "Trending Now",
    key_data: ["Outdoor apparel", "Transitional fits", "Core comfort"],
  },
  {
    key: "Clothing",
    key_data: [
      "View All",
      "T-shirts & Tops",
      "Shirts",
      "Trousers",
      "Jeans",
      "Jackets & Coats",
      "Hoodies & Sweatshirts",
      "Sweaters & Cardigans",
      "Polos",
      "Basics",
      "Blazers & Suits",
      "Shorts",
    ],
  },
  {
    key: "Accessories",
    key_data: [
      "View all",
      "Bags",
      "Belts and Suspenders",
      "Gloves",
      "Hats and Caps",
      "Jewellery",
      "Scarves",
      "Sunglasses",
      "Ties & Bowties",
    ],
  },
  {
    key: "Sport",
    key_data: [
      "View all",
      "New In",
      "Tops",
      "Sweatshirts & Hoodies",
      "Trousers & Joggers",
      "Shorts",
      "Outerwear",
      "Accessories & Equipment",
      "Sport Socks",
      "Training & Gym",
      "Running",
    ],
  },
  {
    key: "Sale",
    key_data: [
      "View all",
      "T-shirts & Tanks",
      "Shirts",
      "Hoodies & Sweatshirts",
      "Cardigans & Jumpers",
      "Blazers & Suits",
      "Jackets & Coats",
      "Trousers",
      "Jeans",
      "Shorts",
      "Underwear",
      "Socks",
      "Nightwear & Loungewear",
      "Swimwear",
      "Premium Selection",
      "Accessories",
      "Shoes",
      "Sport",
    ],
  },
  {
    key: "All Brands",
    key_data: [],
  },
];
export const home = [
  {
    key: "Offers",
    key_data: [
      "Bath Essentials: From ₹249",
      "Bedroom Essentials: From ₹499",
      "Spring cushion covers: From ₹499",
    ],
  },
  {
    key: "New In",
    key_data: ["New In"],
  },
  {
    key: "Sale",
    key_data: [
      "View all",
      "Vases & Decorations",
      "Interior textiles",
      "Bedding & Blankets",
      "Cooking & Dining",
      "Bath & Shower",
      "Storage",
      "Furniture",
      "Lighting",
      "Kids & Baby",
      "Room Fragrance",
      "Flowers & Plants",
      "Sleep & Loungewear",
    ],
  },
  {
    key: "Shop by Room",
    key_data: [
      "Bedroom",
      "Living Room",
      "Kitchen",
      "Bathroom",
      "Nursery",
      "Kids Room",
      "Balcony & Outdoor",
    ],
  },
  {
    key: "Shop by Product",
    key_data: [
      "View all products",
      "Bedding & Blankets",
      "Cooking & Dining",
      "Decorations",
      "Interior textiles",
      "Storage",
      "Bath & Shower",
      "Room Fragrance",
      "Sleep & Loungewear",
      "Kids & Baby",
    ],
  },
  {
    key: "All Brands",
    key_data: [],
  },
];
export const baby = [
  {
    key: "Sale",
    key_data: ["Newborn", "Girls", "Boys", "View All"],
  },
  {
    key: "Life with Baby",
    key_data: ["Guides and inspo"],
  },
  {
    key: "New In",
    key_data: ["Newborn", "Baby"],
  },
  {
    key: "Trending Now",
    key_data: [
      "Character newborn",
      "H&M Adorables",
      "Soft essentials",
      "Sweet spring",
    ],
  },
  {
    key: "Newborn",
    key_data: ["Clothing", "Accessories", "Outerwear"],
  },
  {
    key: "Baby Girl",
    key_data: ["Clothing", "Outerwear", "Accessories"],
  },
  {
    key: "Baby Boy",
    key_data: ["Clothing", "Outerwear", "Accessories"],
  },
  {
    key: "Shop by Product",
    key_data: ["Clothing", "Outerwear", "Accessories"],
  },
];
export const kids = [
  {
    key: "Trending Now",
    key_data: [
      "H&M Adorables",
      "Summer finds",
      "Starting ₹399",
      "Basics",
      "Carnival Outfits/Fancy Dress",
    ],
  },
  {
    key: "New In",
    key_data: ["Kids 2-8Y", "Kids 9-14Y"],
  },
  {
    key: "Sale",
    key_data: [
      "Kids 2-8Y",
      "Kids 9-14Y",
      "Girls 2-8Y",
      "Girls 9-14Y",
      "Boys 2-8Y",
      "Boys 9-14Y",
    ],
  },
  {
    key: "Girls 2-8Y",
    key_data: [
      "Clothing",
      "Outerwear",
      "Accessories",
      "H&M Adorables",
      "Sportswear",
      "Sale",
    ],
  },
  {
    key: "Boys 2-8Y",
    key_data: [
      "Clothing",
      "Outerwear",
      "Accessories",
      "H&M Adorables",
      "Sportswear",
      "Sale",
    ],
  },
  {
    key: "Girls 9-14Y",
    key_data: ["Clothing", "Outerwear", "Accessories", "Sportswear", "Sale"],
  },
  {
    key: "Boys 9-14Y",
    key_data: ["Clothing", "Outerwear", "Accessories", "Sportswear", "Sale"],
  },
];
export const sale = [];
