export const ladies = [
  {
    key: "Offers",
    key_data: ["Member Exclusive Prices", "Sale", "Special Deals"],
  },
  {
    key: "New Arrivals",
    key_data: ["Women's Clothing", "New In", "View All"],
  },
  {
    key: "Trending Now",
    key_data: ["Trending Now", "View All"],
  },
  {
    key: "Clothing",
    key_data: [
      "Tops",
      "Sweatshirts & Hoodies",
      "Knitwear",
      "Sweaters & Cardigans",
      "Jackets & Coats",
      "Dresses",
      "Shirts & Blouses",
      "Blazers & Waistcoats",
      "Jeans",
      "Trousers",
      "Nightwear",
      "Lingerie",
      "Shorts",
      "Skirts",
      "Basics",
      "Swimwear & Beachwear",
      "H&M Edition",
      "Merch & Graphics",
      "Jumpsuits",
      "Loungewear",
      "Socks & Tights",
      "Maternity Wear",
    ],
  },
  {
    key: "Sale",
    key_data: ["Premium Selection", "Care Products"],
  },
  {
    key: "Sport",
    key_data: [
      "New In",
      "Leggings & Tights",
      "Sport Bras",
      "Tops",
      "Hoodies & Sweatshirts",
      "Trousers & Joggers",
      "Shorts",
      "Dresses",
      "Outerwear",
      "Accessories & Equipment",
      "Socks",
      "Active Swimwear",
      "Maternity",
      "Training & Gym",
      "Running",
      "Yoga & Studio",
      "Hiking",
      "Skiing",
      "Racket Sports",
      "Swimming",
    ],
  },
  {
    key: "Accessories",
    key_data: [
      "Bags",
      "Jewellery",
      "Sunglasses",
      "Hair Accessories",
      "Belts",
      "Gloves",
      "Hats",
      "Scarves",
      "Shoes",
    ],
  },
  {
    key: "Shoes",
    key_data: [
      "Boots",
      "Flats",
      "Heels",
      "Loafers",
      "Sandals",
      "Slippers",
      "Slingback",
    ],
  },
];

export const men = [
  {
    key: "Offers",
    key_data: [
      "Member Exclusive Prices",
      "Sweats & Hoodies: From ₹799",
      "Sale",
      "Special Deals",
    ],
  },
  {
    key: "New Arrivals",
    key_data: ["View All", "Clothes", "Shoes & Accessories"],
  },
  {
    key: "Trending Now",
    key_data: [
      "Outdoor Apparel",
      "Core Comfort",
      "Christmas Shop",
      "The Holiday Shop",
      "Gift Guide for Him",
    ],
  },
  {
    key: "Clothing",
    key_data: [
      "View All",
      "Hoodies & Sweatshirts",
      "Shirts",
      "T-shirts & Tops",
      "Jackets & Coats",
      "Trousers",
      "Jeans",
      "Sweaters & Cardigans",
      "Polos",
      "Basics",
      "Blazers & Suits",
      "Shorts",
      "Underwear",
      "Premium Selection",
      "Sleepwear & Loungewear",
      "Swimwear",
      "Socks",
    ],
  },
  {
    key: "Sport",
    key_data: [
      "New In",
      "Tops",
      "Sweatshirts & Hoodies",
      "Trousers & Joggers",
      "Shorts",
      "Outerwear",
      "Accessories & Equipment",
      "Sport Socks",
      "Training & Gym",
      "Running",
      "Hiking",
      "Racket Sports",
    ],
  },
  {
    key: "Accessories",
    key_data: [
      "View All",
      "Bags",
      "Belts & Suspenders",
      "Gloves",
      "Hats & Caps",
      "Jewellery",
      "Scarves",
      "Sunglasses",
      "Ties & Bowties",
      "Shoes",
    ],
  },
  {
    key: "Sustainability",
    key_data: ["H&M Take Care", "Learn More", "Sustainable Materials"],
  },
  {
    key: "The Essentials",
    key_data: ["About", "Core Collection"],
  },
  {
    key: "Spring Lookbook",
    key_data: [
      "Casual Looks",
      "Smart Looks",
      "Street Looks",
      "Party Wear",
      "Office Wear",
      "Loungewear",
    ],
  },
];
export const home = [
  {
    key: "Offers",
    key_data: ["Member Exclusive Prices", "Sale", "Special Deals"],
  },
  {
    key: "New Arrivals",
    key_data: ["New Products", "Christmas Shop", "Holiday Shop", "Gifts"],
  },
  {
    key: "Shop by Room",
    key_data: [
      "Bedroom",
      "Living Room",
      "Bathroom",
      "Nursery",
      "Kids Room",
      "Kitchen",
      "Balcony & Outdoor",
    ],
  },
  {
    key: "Shop by Product",
    key_data: [
      "View All",
      "Interior Textiles",
      "Bedding & Blankets",
      "Decorations",
      "Cooking & Dining",
      "Bath & Shower",
      "Storage",
      "Sleep & Loungewear",
      "Kids & Baby",
      "Room Fragrance",
    ],
  },
  {
    key: "Trending Now",
    key_data: [
      "Home Essentials",
      "Colorburst Collection",
      "Scented Candles",
      "Latest Trends",
    ],
  },
  {
    key: "Sustainability",
    key_data: ["Meet the Maker", "Eco-Friendly Products"],
  },
  {
    key: "Magazine",
    key_data: ["Magazine", "Style Guides", "Home Inspiration"],
  },
];

export const kids = [
  {
    key: "Offers",
    key_data: ["Member Exclusive Prices", "Shop Now", "Sale"],
  },
  {
    key: "Trending Now",
    key_data: ["Christmas Shop", "H&M Adorables", "The Character Shop"],
  },
  {
    key: "New Arrivals",
    key_data: [
      "Kids 2-8Y",
      "Kids 9-14Y",
      "Girls 2-8Y",
      "Boys 2-8Y",
      "Girls 9-14Y",
      "Boys 9-14Y",
    ],
  },
  {
    key: "Clothing",
    key_data: [
      "Outerwear",
      "Accessories",
      "H&M Adorables",
      "Sportswear",
      "Sale",
    ],
  },
  {
    key: "Shop by Product",
    key_data: [
      "View all",
      "New Arrivals",
      "Clothing",
      "Outerwear",
      "Accessories",
      "Shoes",
      "Sale",
    ],
  },
  {
    key: "Sustainability",
    key_data: ["H&M Take Care", "Learn More"],
  },
];

export const sale = [
  {
    key: "Men",
    key_data: [
      "View All",
      "T-shirts & Tank Tops",
      "Shirts",
      "Trousers",
      "Hoodies & Sweatshirts",
      "Jeans",
      "Shoes",
      "Shorts",
      "Cardigans & Jumpers",
      "Jackets & Coats",
      "Knitwear",
      "Basics",
      "Suits & Blazers",
      "Underwear & Innerwear",
      "Socks",
      "Accessories",
      "Sportswear",
      "Care Products",
      "Sleepwear & Loungewear",
    ],
  },
  {
    key: "Women",
    key_data: [
      "View All",
      "Tops & T-shirts",
      "Dresses",
      "Trousers",
      "Blazers",
      "Shirts & Blouses",
      "Jeans",
      "Shoes",
      "Accessories",
      "Lingerie",
      "Nightwear",
      "Sweatshirts & Hoodies",
      "Cardigans & Sweaters",
      "Knitwear",
      "Jackets & Coats",
      "Loungewear",
      "Sportswear",
      "Skirts",
      "Shorts",
      "Basics",
    ],
  },
  {
    key: "Dividend",
    key_data: [
      "View All",
      "Tops",
      "Jeans",
      "Dresses",
      "Shirts & Blouses",
      "Accessories",
      "Divided - Basics",
      "Trousers & Leggings",
      "Divided - Skirts",
      "Shorts",
      "Underwear & Nightwear",
      "Swimwear",
      "Shoes",
      "Cardigans & Jumpers",
      "Hoodies & Sweatshirts",
      "Jackets & Coats",
      "Care Products",
      "Sale",
    ],
  },
  {
    key: "Kids",
    key_data: [
      "View All",
      "New Arrivals",
      "Clothing",
      "Outerwear",
      "Accessories",
      "Shoes",
      "Sale",
    ],
  },
  {
    key: "Sports",
    key_data: [
      "View All",
      "New Arrivals",
      "Clothing",
      "Outerwear",
      "Accessories & Equipment",
    ],
  },
];
